import type { Metadata } from 'next'
import { Geist, Geist_Mono, Playwrite_IN, Playfair_Display } from 'next/font/google'
import '@/styles/globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin-ext']
})

const playwrite = Playwrite_IN({
	variable: '--font-playwrite'
})

const playfair = Playfair_Display({
	variable: '--font-playfair',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Coffee Town',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
				<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
				<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${playwrite.variable} ${playfair.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	)
}
